description: >
  This is a sample executor using Docker, wordpress, phpmyadmin and mysql.
  # What is this executor?
  # Descriptions should be short, simple, and clear.
docker:
  - image: wordpress:latest
  - image: phpmyadmin/phpmyadmin
  - image: mysql:8.0
